# nacos\u7684\u914D\u7F6E\uFF0C\u5728\u9879\u76EE\u521D\u59CB\u5316\u7684\u65F6\u5019\uFF0C\u8981\u4FDD\u8BC1\u5148\u4ECE\u914D\u7F6E\u4E2D\u5FC3\u8FDB\u884C\u914D\u7F6E\u7684\u62C9\u53D6\uFF0C\u62C9\u53D6\u914D\u7F6E\u4E4B\u540E\uFF0C\u624D\u80FD\u4FDD\u8BC1\u9879\u76EE\u7684\u6B63\u5E38\u542F\u52A8
# springboot\u7684\u7684\u914D\u7F6E\u6587\u4EF6\u52A0\u8F7D\u662F\u5B58\u5728\u4F18\u5148\u987A\u5E8F\u7684\uFF0Cbootstrap.yml\u4F18\u5148\u7EA7\u9AD8\u4E8Eapplication.properties
# \u5728nacos\u4E2D\u914D\u7F6E\u7684\u7684dataid\u89C4\u5219\uFF0C\u53C2\u8003\uFF1A https://nacos.io/zh-cn/docs/quick-start-spring-cloud.html
#\u5728 Nacos Spring Cloud \u4E2D\uFF0CdataId \u7684\u5B8C\u6574\u683C\u5F0F\u5982\u4E0B\uFF1A${prefix}-${spring.profiles.active}.${file-extension}
#prefix \u9ED8\u8BA4\u4E3A spring.application.name \u7684\u503C\uFF0C\u4E5F\u53EF\u4EE5\u901A\u8FC7\u914D\u7F6E\u9879 spring.cloud.nacos.config.prefix\u6765\u914D\u7F6E\u3002
#spring.profiles.active \u5373\u4E3A\u5F53\u524D\u73AF\u5883\u5BF9\u5E94\u7684 profile\uFF0C\u8BE6\u60C5\u53EF\u4EE5\u53C2\u8003 Spring Boot\u6587\u6863\u3002
#    \u6CE8\u610F\uFF1A\u5F53 spring.profiles.active \u4E3A\u7A7A\u65F6\uFF0C\u5BF9\u5E94\u7684\u8FDE\u63A5\u7B26 - \u4E5F\u5C06\u4E0D\u5B58\u5728\uFF0CdataId \u7684\u62FC\u63A5\u683C\u5F0F\u53D8\u6210 ${prefix}.${file-extension}
#file-exetension \u4E3A\u914D\u7F6E\u5185\u5BB9\u7684\u6570\u636E\u683C\u5F0F\uFF0C\u53EF\u4EE5\u901A\u8FC7\u914D\u7F6E\u9879 spring.cloud.nacos.config.file-extension \u6765\u914D\u7F6E\u3002\u76EE\u524D\u53EA\u652F\u6301 properties \u548C yaml \u7C7B\u578B\u3002
#    \u901A\u8FC7 Spring Cloud \u539F\u751F\u6CE8\u89E3 @RefreshScope \u5B9E\u73B0\u914D\u7F6E\u81EA\u52A8\u66F4\u65B0\uFF1A
# \u542F\u52A8\u9879\u76EE\u4E4B\u524D\u5FC5\u987B\u5148\u914D\u7F6E\u5176\u914D\u7F6E\u6587\u4EF6
# \u6DFB\u52A0\u914D\u7F6E\u65F6\u5176DataID\u7684\u516C\u5F0F\uFF1A${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension} \uFF0C
#\u5373\uFF1A\u9879\u76EE\u540D\u79F0-\u5F53\u524D\u73AF\u5883.\u6587\u4EF6\u540E\u7F00
server:
  port: 9048
spring:
  application:
    name: day-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        # \u914D\u7F6E\u6587\u4EF6\u7684\u540E\u7F00
        file-extension: yml
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods:
              - OPTIONS
              - GET
              - POST
            max-age: 3600
      discovery:
        locator:
          enabled: true
      default-filters:
        - StripPrefix=1
      routes:
        - id: day-today
          uri: lb://day-today
          predicates:
            - Path=/today/**
        - id: day-yesday
          uri: lb://day-yesday
          predicates:
            - Path=/yesday/**
# \u65E5\u5FD7\u914D\u7F6E
logging:
  config: classpath:logback-spring.xml
  level:
    com.day.gateway: debug
